spring.application.name=auth-service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pharmatrace_auth
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8081
